//! The vocabulary the server advertises.
//!
//! Every list here is *generated* from the library. None of it is written out
//! a second time, for the reason `cli/values.rs` gives at length: the CLI once
//! kept hand-written copies of these names -- 31 birthmarks and 64 analyses --
//! and they went stale in three directions at once (#25). A model guessing at
//! `op-3gram-freq-cosine` has no `--help` to fall back on, so a list that has
//! drifted is worse here than it was there.
//!
//! The one exception is the aggregators, which the library does not enumerate.
//! They are listed by hand and the tests check every name against
//! `Aggregator::from_str`, so the list cannot advertise something the parser
//! would refuse.

use clap::ValueEnum;
use oinkie::prelude::*;
use rmcp::schemars;
use serde::Serialize;

#[derive(Debug, Serialize, schemars::JsonSchema, PartialEq, Eq)]
pub struct Named {
    pub name: String,
    pub description: String,
}

#[derive(Debug, Serialize, schemars::JsonSchema, PartialEq, Eq)]
pub struct AlgorithmInfo {
    pub name: String,
    pub description: String,
    /// The birthmark shape this algorithm operates on. An algorithm paired
    /// with a birthmark of another shape is refused, naming the pairing that
    /// was meant.
    pub operates_on: String,
}

#[derive(Debug, Serialize, schemars::JsonSchema, PartialEq, Eq)]
pub struct Vocabulary {
    pub birthmarks: Vec<Named>,
    pub algorithms: Vec<AlgorithmInfo>,
    /// Every canonical `{birthmark}-{algorithm}` name, which is what the
    /// `analysis` argument takes. Generated by pairing each birthmark with the
    /// algorithms that operate on its shape, so it cannot offer a pairing that
    /// would be refused.
    pub analyses: Vec<String>,
    pub strategies: Vec<Named>,
    pub aggregators: Vec<Named>,
    pub notes: Vec<String>,
}

/// The aggregators, which the library does not enumerate.
///
/// `Aggregator` has a `FromStr` and no list, so this is the one thing here
/// that is written rather than generated. The tests parse every name below,
/// which is the closest available substitute for generating it.
const AGGREGATORS: &[(&str, &str)] = &[
    (
        "hungarian",
        "Optimal one-to-one matching between the elements of the two birthmarks, maximising the total score. The default.",
    ),
    (
        "topn:all",
        "For each element on the left, take its best match on the right, without requiring the matching to be one-to-one. \"topn\" alone means the same.",
    ),
    (
        "topn:5",
        "As topn:all, but considering only the 5 most similar. Any count of at least 1 works: \
         the name is topn: followed by the number, and 5 here is only an example.",
    ),
];

fn named_variants<T: ValueEnum>() -> Vec<Named> {
    T::value_variants()
        .iter()
        .filter_map(|v| v.to_possible_value())
        .map(|pv| Named {
            name: pv.get_name().to_string(),
            // Empty rather than a panic. `oinkie info` unwraps this and a test
            // guards it; here the same missing doc comment would take down a
            // running server, so it is a test's job rather than a runtime one.
            description: pv.get_help().map(|h| h.to_string()).unwrap_or_default(),
        })
        .collect()
}

pub fn vocabulary() -> Vocabulary {
    Vocabulary {
        birthmarks: BirthmarkType::advertised()
            .map(|bt| Named {
                name: bt.to_string(),
                description: bt.description(),
            })
            .collect(),
        algorithms: Algorithm::value_variants()
            .iter()
            .filter_map(|a| a.to_possible_value().map(|pv| (a, pv)))
            .map(|(a, pv)| AlgorithmInfo {
                name: pv.get_name().to_string(),
                description: pv.get_help().map(|h| h.to_string()).unwrap_or_default(),
                operates_on: a.shape().description().to_string(),
            })
            .collect(),
        analyses: AnalysisType::advertised_names().collect(),
        strategies: named_variants::<PairingStrategy>(),
        aggregators: AGGREGATORS
            .iter()
            .map(|(name, description)| Named {
                name: (*name).to_string(),
                description: (*description).to_string(),
            })
            .collect(),
        notes: vec![
            format!(
                "The k-gram names listed stop at k={MAX_ADVERTISED_K}, but any k parses: \
                 'op-12gram-set' is a valid birthmark and 'op-12gram-set-dice' a valid analysis."
            ),
            "An analysis is named '{birthmark}-{algorithm}'. The algorithm has to operate on the \
             birthmark's shape; a pairing that does not is refused, naming the one that was meant."
                .to_string(),
            "An aggregator is 'hungarian', 'topn:all' or 'topn:' followed by a count of at \
             least 1. The listed 'topn:5' is one example of the last, not the only value it \
             takes -- the same way the k-gram list above is a sample rather than a limit."
                .to_string(),
            "An algorithm's own name and the name it carries inside an analysis can differ: \
             'weighted-jaccard' is the algorithm, and the analysis is spelled \
             'op-freq-weightedjaccard'. Both spellings parse in an analysis name, so either \
             composes; the algorithm argument itself takes the hyphenated form."
                .to_string(),
            "Inputs are files already lifted to the Oinkie IR (the JSON that 'oinkie lift' \
             writes). Lifting itself is not exposed over MCP: it runs a whole decompiler per \
             binary, for as long as that binary takes. Run 'oinkie lift' yourself first."
                .to_string(),
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    /// The whole point of this module: what it advertises is what the library
    /// generates, not a copy of it. `cli/values.rs` asserts the same thing for
    /// clap's lists, after two hand-written ones went stale in three
    /// directions at once (#25).
    #[test]
    fn test_the_birthmarks_are_the_ones_the_library_generates() {
        let offered = vocabulary()
            .birthmarks
            .into_iter()
            .map(|n| n.name)
            .collect::<Vec<_>>();
        let expected = BirthmarkType::advertised()
            .map(|bt| bt.to_string())
            .collect::<Vec<_>>();
        assert_eq!(offered, expected);
        assert!(offered.contains(&"op-3gram-set".to_string()));
    }

    #[test]
    fn test_the_analyses_are_the_ones_the_library_generates() {
        assert_eq!(
            vocabulary().analyses,
            AnalysisType::advertised_names().collect::<Vec<_>>()
        );
    }

    #[test]
    fn test_the_algorithms_are_the_ones_the_library_generates() {
        let offered = vocabulary()
            .algorithms
            .into_iter()
            .map(|a| a.name)
            .collect::<Vec<_>>();
        let expected = Algorithm::value_variants()
            .iter()
            .filter_map(|a| a.to_possible_value())
            .map(|pv| pv.get_name().to_string())
            .collect::<Vec<_>>();
        assert_eq!(offered, expected);
    }

    /// The algorithm list and the analysis list do not spell every algorithm
    /// the same way, and that is correct rather than a slip: an `algorithm`
    /// argument is parsed by clap, which knows `weighted-jaccard`, while an
    /// analysis name is parsed by the library's own split, which produced
    /// `weightedjaccard` from `cli_name`. Both parse inside an analysis (#71).
    ///
    /// Asserted rather than merely written down, because the two lists sit
    /// next to each other in one tool result and a reader will notice.
    #[test]
    fn test_the_two_spellings_of_an_algorithm_both_work() {
        let hyphenated = "weighted-jaccard";
        let joined = "weightedjaccard";
        assert!(
            vocabulary().algorithms.iter().any(|a| a.name == hyphenated),
            "the algorithm list should carry the spelling its own argument takes"
        );
        assert!(
            vocabulary()
                .analyses
                .iter()
                .any(|n| n == &format!("op-freq-{joined}")),
            "the analysis list should carry the spelling the library generates"
        );
        // and either composes into a name that parses
        for spelling in [hyphenated, joined] {
            let name = format!("op-freq-{spelling}");
            assert!(
                AnalysisType::try_from(name.as_str()).is_ok(),
                "{name} should parse"
            );
        }
        assert!(
            vocabulary()
                .notes
                .iter()
                .any(|n| n.contains(hyphenated) && n.contains(joined)),
            "the difference has to be explained where both lists are returned"
        );
    }

    /// Every advertised analysis has to parse, or the list is offering
    /// something that would be refused when used.
    #[test]
    fn test_every_advertised_analysis_parses() {
        for name in vocabulary().analyses {
            assert!(
                AnalysisType::try_from(name.as_str()).is_ok(),
                "advertised but refused: {name}"
            );
        }
    }

    /// The aggregators are the one list written here rather than generated,
    /// because `Aggregator` has a `FromStr` and no enumeration. Parsing each
    /// one is the closest substitute: the list cannot advertise a name the
    /// parser would refuse.
    ///
    /// Verbatim, with nothing standing in. The list used to carry `topn:N` and
    /// this test replaced the `N` with a 3 before parsing -- so it asserted
    /// that *some* name parsed, not the one being advertised, and `topn:N`
    /// reached a reader as though it were a value they could send.
    #[test]
    fn test_every_advertised_aggregator_parses_verbatim() {
        for agg in vocabulary().aggregators {
            assert!(
                Aggregator::from_str(&agg.name).is_ok(),
                "advertised but refused: {}",
                agg.name
            );
        }
    }

    /// The listed `topn:` value is an example, and a reader has to be told so
    /// or they will take it for the only one.
    #[test]
    fn test_the_notes_say_the_topn_count_is_free() {
        let notes = vocabulary().notes.join(" ");
        assert!(notes.contains("topn:"), "{notes}");
        for n in [
            "topn:1",
            "topn:5",
            "topn:97",
            "topn:all",
            "topn",
            "hungarian",
        ] {
            assert!(Aggregator::from_str(n).is_ok(), "{n} should parse");
        }
        assert!(
            Aggregator::from_str("topn:N").is_err(),
            "the placeholder must not be advertised as a value"
        );
        assert!(Aggregator::from_str("topn:0").is_err(), "0 is refused");
    }

    /// A missing doc comment would otherwise reach a model as an empty string,
    /// which reads as "this option means nothing" rather than as a bug here.
    /// `oinkie info` guards the same hole with an `unwrap`; a server cannot
    /// panic, so the guard is here instead.
    #[test]
    fn test_nothing_is_advertised_without_a_description() {
        let v = vocabulary();
        for n in v
            .birthmarks
            .iter()
            .chain(&v.strategies)
            .chain(&v.aggregators)
        {
            assert!(!n.description.is_empty(), "{} has no description", n.name);
        }
        for a in &v.algorithms {
            assert!(!a.description.is_empty(), "{} has no description", a.name);
            assert!(!a.operates_on.is_empty(), "{} has no shape", a.name);
        }
    }

    /// The advertised list stops at a k; the parser does not. A model told
    /// only the list would never try the k it actually wants.
    #[test]
    fn test_the_notes_say_the_k_list_is_not_the_limit() {
        let notes = vocabulary().notes.join(" ");
        assert!(notes.contains(&MAX_ADVERTISED_K.to_string()), "{notes}");
        let beyond = format!("op-{}gram-set-dice", MAX_ADVERTISED_K + 1);
        assert!(
            AnalysisType::try_from(beyond.as_str()).is_ok(),
            "the note claims {beyond} parses"
        );
    }

    /// Lifting is not offered here, and the reason has to reach the reader:
    /// a model that does not know will ask for it and be confused when no
    /// such tool exists.
    #[test]
    fn test_the_notes_say_lifting_is_not_offered() {
        let notes = vocabulary().notes.join(" ").to_lowercase();
        assert!(notes.contains("lift"), "{notes}");
    }
}
