name: build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "19.1.7"

      - name: Setup Rust LLVM coverage tools
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov llvmenv

      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Test & Build
        env:
          LLVM_SYS_191_PREFIX: "${{ env.LLVM_PATH }}"
        run: |
          cargo build
          cargo llvm-cov --lcov --output-path coverage.lcov

      - name: Send coverage to coveralls
        uses: coverallsapp/github-action@master
        if: matrix.os == 'ubuntu-latest'
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
